downgrade typing-extensions
The jenkins build is failing with this error, since the
typing-extensions upgrade:
> selenium.common.exceptions.WebDriverException: Message: unknown error:
> unable to discover open pages

I want to see if this revert fixes the issue.

reverts 940d46044a29076e5af27173634e23f41506c79b