Revert "Adding Professor Youngren's fix to LevelSurface"
This reverts commit 3f3b80e1f3d23c427b1f11306030164c6b19c0ed.

These changes cause this error when rendering the Level surface:
```
ReferenceError: pts is not defined
```

I tried to fix the issue, but it just led to more problems. Let's just
revert these changes until we get it working.